[profile.default]
src = "src"
out = "out"
solc_version = '0.8.19'
libs = ["lib"]

optimizer = true
optimizer_runs = 200 

remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate=lib/solmate/'
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
